env:
  K: 800
  Nj0: 74
  Ns0: 74
  Na0: 221
  C0: 197
  H0: 1.0
  sj_base: .nan
  ss_base: .nan
  sa_base: .nan
  fecundity_per_adult: 0.11872026214640023
  habitat_repro_sensitivity: 0.2
  lead_j_base: 0.06
  lead_s_base: 0.12
  lead_a_base: 0.05
  lead_mitigation_effect: 0.3
  habitat_lead_sensitivity: 0.8
  disaster_base_prob: 0.0
  disaster_mortality_frac: 0.4
  disaster_habitat_sensitivity: 0.8
  release_base_survival: 0.55
  release_density_sensitivity: 0.2
  captive_recruitment_rate: 0.05
  C_cap: 400
  habitat_baseline: 1.0
  habitat_recovery_rate: 0.03
  habitat_mitigation_effect: 0.08
  habitat_min: 0.3
  habitat_max: 1.3
reward:
  target_low: 650
  target_high: 700
  w_low: 20
  w_high: 1
  lambda_release: 0.2
  lambda_mitigation: 0.1
  lambda_disaster: 20.0
sim:
  seed: 0
  horizon: 120
  N_rollouts: 20
actions:
  release_min: 0
  release_max: 20
  release_step: 1
  mitigation_min: 0.0
  mitigation_max: 1.0
  mitigation_step: 0.1
train:
  gamma: 0.99
  n_iterations: 25
  n_episodes: 300
  horizon: 100
  random_seed: 0
  save_model_path: trained_fqi_age3.npy
